<?php

return [

    'title' => 'Upozornenie na riziká',
    'text' => 'Upozornenie na riziká spojené s nehnuteľnosťami',
    'text2' => 'Táto webová stránka má len informačný charakter. Táto webová stránka nemá za cieľ poskytovať žiadne účtovné, právne, daňové alebo investičné rady alebo odporúčania. Žiadne informácie uvedené na tejto webovej stránke nepredstavujú ponuku alebo navádzanie na kúpu alebo predaj akéhokoľvek cenného papiera alebo fondu v ktorejkoľvek jurisdikcii, kde je ponúkanie vyššie uvedeného zákonné. Služby uvedené na týchto webových stránkach môžu byť ponúkané a predávané iba osobám, ktoré sa nachádzajú na území, v ktorom sú ' . env('APP_NAME') . ' alebo jej dcérske spoločnosti riadne zaregistrované alebo oslobodené od registrácie.',
    'text3' => 'Investovanie do nehnuteľností podlieha určitým rizikám, a to najmä: ekonomické (lokálne, národné a medzinárodné hospodárske podmienky); ponuka a dopyt po nehnuteľnostiach; finančné schopnosti nájomcov, kupujúcich a predávajúcich nehnuteľností; zmeny v úrokových sadzbách; zmeny zákonov alebo predpisov o životnom prostredí; zmeny právnej regulácie v oblasti plánovania výstavby a iné verejnoprávne zásahy; fiškálna a menová politika; zmeny spojené s právnym, regulačným a daňovým prostredím; zmeny sadzieb daní z nehnuteľností; právne vady nehnuteľností; negatívne zmeny ekonomiky spojené s prepadom cestovného ruchu a poklesom maloobchodu; nepredvídateľné straty; vplyv vyššej moci; teroristické útoky; straty, ktoré neboli poistené alebo neboli poistiteľné a iné faktory, ktoré nebolo možné odvrátiť ani pri vynaložení dostatočnej odbornej starostlivosti manažmentu. Okrem vyššie uvedených rizík by majiteľ dlhopisu mal brať na vedomie, že hodnota nehnuteľností podlieha dlhodobým cyklickým trendom, ktoré spôsobujú značnú cenovú nestálosť (volatilitu). Koncentrované investovanie do nehnuteľností a investície zabezpečené nehnuteľnosťami sú vystavené vyššie špecifikovaným rizikám bez možnosti rozloženia rizík, pretože nejde o kolektívne investovanie v zmysle osobitných právnych predpisov.',
    'text4' => 'Investovanie do nehnuteľností je z dôvodu koncentrácie v tomto špecifickom odvetví, oblasti resp. v geografickej lokalite vystavené vyššiemu trhovému riziku. Investície do nehnuteľností môžu podliehať najmä rizikám poklesu cenovej hladiny nehnuteľností, rizikám spojenými so všeobecnými a ekonomickými podmienkami trhu, rizikám týkajúcich sa zmien hodnoty nehnuteľností, ktoré kryjú realitnú investíciu a nesplácaním úverov od dlžníkov.',
    'text5' => 'Hodnota investície a príjmy z nej môžu kolísať a vaša investícia nie je garantovaná. Predošlé zisky nie sú zárukou budúcich výnosov. Majte na pamäti, že investovanie na zahraničných trhoch podlieha špecifickým rizikám cudzej meny, ako aj politickým a ekonomickým rizikám. Výmenné kurzy môžu spôsobiť, že hodnota podkladových zahraničných investícií klesne alebo stúpne. Investície v rozvíjajúcich sa trhoch môžu byť z dôvodu makroekonomickej alebo politickej situácie nestálejšie ako na iných trhoch, čo predstavuje zvýšené riziko pre investovaný kapitál, a teda aj uvedené skutočnosti môžu ovplyvniť skutočnú hodnotu investície.',

];