<?php

return [

    'title' => 'Risk disclosure',
    'text' => 'Real Estate Risk Disclosure',
    'text2' => 'This website is intended for general information purposes. This website is not intended to provide any accounting, legal, regulatory, tax, or investment advice or recommendations. No information contained on this website constitutes an offer, or a solicitation to buy or sell any security or fund in any jurisdiction where such offer or solicitation would be lawful. The services referred to on this website may be offered and sold only to persons where ' . env('APP_NAME') . ' or its subsidiaries are duly registered or exempt from registration.',
    'text3' => 'Investment is subject to certain risks associated with the real estate industry in general, including: local, national and international economic conditions; the supply and demand for properties; the financial conditions for tenants, buyers and sellers of properties; changes in interest rates; changes in environmental laws or regulations, planning laws and other governmental roles and fiscal and monetary policies; changes in real property tax rates; negative developments in the economy that depress travel and retail activity; uninsured casualties; force majeure acts, terrorist events, under-insured or uninsurable losses; and other factors that are beyond the reasonable control of the Manager. In addition, as recent experience has demonstrated, real estate assets are subject to long-term cyclical trends that give rise to significant volatility in values. Investment is disproportionately exposed to the foregoing risks because of its concentration in real estate and real estate-related investments.',
    'text4' => 'Real estate investing may be subject to a higher degree of market risk because of concentration in a specific industry, sector, or geographic sector. Real estate investments may be subject to risks including, but not limited to, declines in the value of real estate, risks related to general and economic conditions, changes in the value of the underlying property owned by the trust and defaults by borrowers.',
    'text5' => 'The value of investments and the income from them may fluctuate and your investment is not guaranteed. Past performance is no guarantee of future results. Please note that investments in foreign markets are subject to special currency, political, and economic risks. Exchange rates may cause the value of underlying overseas investments to go down or up. Investments in emerging markets may be more volatile than other markets and the risk to your capital is therefore greater. Also, the economic and political situations may be more volatile than in established economies and these may adversely influence the value of investments made.',

];