<?php

return [

    'title' => 'Openbaarmaking van risicos',
    'text' => 'Openbaarmaking van onroerendgoedrisico',
    'text2' => 'Deze website is bedoeld voor algemene informatiedoeleinden. Deze website is niet bedoeld om advies of aanbevelingen op het gebied van boekhouding, wetgeving, regelgeving, belastingen of investeringen te verstrekken. Geen enkele informatie op deze website vormt een aanbod, of een verzoek om een effect of fonds te kopen of verkopen in enig rechtsgebied waar een dergelijk aanbod of verzoek rechtmatig zou zijn. De op deze website genoemde diensten mogen alleen worden aangeboden en verkocht aan personen waar ',
    'text3' => 'Beleggingen zijn onderworpen aan bepaalde risicos verbonden aan de vastgoedsector in het algemeen, waaronder: lokale, nationale en internationale economische omstandigheden; vraag en aanbod van onroerend goed; de financiële voorwaarden voor huurders, kopers en verkopers van onroerend goed; veranderingen in rentetarieven; veranderingen in milieuwetten of -regelgeving, planningswetten en andere regeringsrollen en fiscaal en monetair beleid; wijzigingen in de tarieven van de onroerendgoedbelasting; negatieve ontwikkelingen in de economie die de reis- en detailhandelsactiviteit drukken; onverzekerde slachtoffers; overmacht, terroristische gebeurtenissen, onderverzekerde of onverzekerbare verliezen; en andere factoren die buiten de redelijke controle van de Beheerder vallen. Zoals recente ervaring heeft aangetoond, zijn vastgoedactiva bovendien onderhevig aan cyclische trends op lange termijn die aanleiding geven tot aanzienlijke volatiliteit in waarden. Beleggingen zijn onevenredig blootgesteld aan de bovengenoemde risicos vanwege hun concentratie in onroerend goed en vastgoedgerelateerde beleggingen.',
    'text4' => 'Investeren in onroerend goed kan een hoger marktrisico lopen vanwege concentratie in een specifieke industrie, sector of geografische sector. Vastgoedinvesteringen kunnen onderhevig zijn aan risicos, waaronder, maar niet beperkt tot, waardeverminderingen van onroerend goed, risicos in verband met algemene en economische omstandigheden, veranderingen in de waarde van de onderliggende eigendom van de trust en wanbetalingen door kredietnemers.',
    'text5' => 'De waarde van beleggingen en de inkomsten daaruit kunnen fluctueren en uw belegging is niet gegarandeerd. In het verleden behaalde resultaten bieden geen garantie voor de toekomst. Merk op dat beleggingen in buitenlandse markten onderhevig zijn aan speciale valuta-, politieke en economische risicos. Wisselkoersen kunnen ervoor zorgen dat de waarde van onderliggende buitenlandse beleggingen daalt of stijgt. Beleggingen in opkomende markten kunnen volatieler zijn dan andere markten en het risico voor uw kapitaal is daarom groter. Ook kunnen de economische en politieke situaties volatieler zijn dan in gevestigde economieën en deze kunnen de waarde van de investeringen negatief beïnvloeden.',

];