<?php

return [

    'title' => 'FAQ',
    '1' => '1. Wie finanziere ich meinen ersten Immobilien Deal?',
    '1a' => 'Es gibt eine Reihe von Optionen, wenn es um die Finanzierung Ihres ersten Immobiliengeschäftes geht. Sie können immer eine konventionelle Vorgehensweise wählen, indem Sie ein Darlehen von einem traditionellen Kreditgeber, d. H. Großen Bankinstituten, erwerben. Sie können jedoch immer für einen privaten oder harten Geldverleiher entscheiden. Private Kreditgeber sind in Bezug auf ihre Kreditanforderungen weniger streng und verlangen daher in der Regel höhere Zinssätze. Der Großhandel ist eine weitere praktikable Option für Anleger, die gerade erst anfangen, da sie keine Anzahlung oder das persönliche Kapital des Anlegers benötigen. In den meisten Fällen sparen neue Investoren die Profite ein, die sie durch den Großhandel erzielen, um sie als Anzahlung für eine Reha zu verwenden oder Immobilien zu kaufen und zu halten.',
    '2' => '2. Ist es notwendig, als Investor eine Immobilienlizenz zu erhalten?',
    '2a' => 'Es gibt sowohl Vor- als auch Nachteile, wenn es darum geht, ob Investoren eine Immobilienlizenz erwerben sollten oder nicht. Wenn Sie als lizenzierter Agent in Immobilien investieren, haben Sie unbegrenzten Zugang zu Immobilien, die auf der MLS gelistet sind. Mit einer Lizenz haben Sie auch die Möglichkeit, einen größeren Gewinn zu erzielen, da Sie keinen Prozentsatz Ihrer Einnahmen an den Agenten abgeben müssen, mit dem Sie gearbeitet hätten. Das Erlangen einer Lizenz öffnet auch die Tür zu einem ganz neuen Netzwerk-Kanal, der eine der besten Möglichkeiten ist, Angebote zu finden. Bedenken Sie auch, dass es Ihnen ohne Lizenz möglich ist, mit einer Vielzahl von Agenten zu arbeiten, die sich alle auf verschiedene Nischen spezialisiert haben und Ihnen die Möglichkeit geben, Ihre Arten von Deals zu diversifizieren. Jedoch wird man nicht einfach so ein lizenzierter Immobilienmakler; Sie müssen viel Zeit, Energie und sogar Geld investieren, um regelmäßig praktizieren zu können. Letztendlich kommt es auf die konkrete Person und ihre Ziele an, wenn es um die Beantwortung dieser Immobilien-Fragen geht.',
    '3' => '3. Was bedeutet ARV?',
    '3a' => 'Das ARV einer Immobilie bezieht sich auf ihren Nach-Reparatur-Wert (After Repair Value). Zu lernen, wie der ARV einer Immobilie genau berechnet wird, ist eine Fähigkeit, die selbst die besten Investoren noch nicht perfektioniert haben. Um festzustellen, ob eine bestimmte Immobilie sich für einen Deal  lohnt, müssen Anleger zunächst den Preis der Immobilie beachten. Des Weiteren ist es nötig das Eigentum zu besichtigen und die Kosten der Reparaturen zu schätzen. Schließlich müssen Sie diese Zahlen analysieren, um zu überprüfen, ob das ARV größer als die ursprünglichen Kosten der Immobilie (plus die Reparaturen) sind oder nicht. Wenn Ihr berechneter ARV nicht mindestens 10 Prozent höher als die Immobilie plus Reparaturen ist, ist es wahrscheinlich, dass Ihre Gewinne minimal sind.',
    '4' => '4. Was sind passende Strategien um auszusteigen?',
    '4a' => 'Als ersten Schritt, gilt es die Entscheidung treffen, seinen Job zu machen. Es gibt drei grundlegende Ausstiegsstrategien, auf die sich die Anleger konzentrieren können, darunter: Großhandel, Reha und Vermietung. Jede hat ihre eigenen Vor- und Nachteile und hängt letztlich von den Zielen und Vorlieben des Einzelnen ab. Für diejenigen, die eher Geld verdienen wollen, ist die ideale Ausstiegs-Strategie der Großhandel, da die Anleger in der Lage sind, das Geschäft in nur zwei Tagen abzuschließen. Eine der beliebtesten Ausstiegsstrategien-Strategien, Rehabbing, ist perfekt für diejenigen mit einem Auge für Design und die Neigung, sich die Hände schmutzig zu machen. Wenn es darum geht, langfristiges Vermögen aufzubauen, sollten Sie Mietobjekte zu Ihrem Portfolio hinzufügen.',
    '5' => '5. Was sind die besten Marketing-Strategien für neue Investoren?',
    '5a' => 'Es gibt heutzutage so viele Marketingstrategien für Immobilieninvestoren, dass man diese kaum zählen kann. Direkte Post-Kampagnen eignen sich hervorragend für neue Investoren, da sie ihre Botschaft, Zielgruppe und Kampagne skalieren können. Die Umsetzung einer Post-Kampagne führt garantiert zu Ergebnissen, da ein konkretes Stück Post potenziellen Kunden eine physische Verbindung mit Ihrer Marke ermöglicht. Wenn Sie die Ergebnisse Ihrer Post-Kampagne verfolgen, können Sie auch feststellen, ob Sie sich auf einen bestimmten Markt oder eine Nische konzentrieren möchten. Wenn Sie z. B. Ihr Poststück an eine Nachlassliste, eine kürzlich ausgeschlossene Liste und eine Steuerstrafliste senden und die meisten Anrufe von denen auf der Steuerstrafliste erhalten, wissen Sie, wie Sie Ihre Kampagne in Zukunft noch effektiver gestalten können. ',
    '6' => '6. Gibt es Steuervorteile beim Investieren in Immobilien',
    '6a' => 'Die Steuervorteile, die die Investition in Immobilien bringen, sind endlos. Ein Vermieter zu werden, ist jedoch der einfachste Weg, diese Vorteile zu erhalten; aber sicher nicht der einzige Weg. Wenn Sie eine Immobilie mieten, können Sie eine Reihe von Aufwendungen abziehen, einschließlich, aber nicht beschränkt auf Abschreibungen, Reparaturen, Zinsen und Steuern, die sich auf das gemeinsame Eigentum beziehen. Die Steuervorteile, die die Investition in Immobilien bringen, sind endlos. Ein Vermieter zu werden, ist jedoch der einfachste Weg, diese Vorteile zu erhalten; aber sicher nicht der einzige Weg. Wenn Sie eine Immobilie mieten, können Sie eine Reihe von Aufwendungen abziehen, einschließlich, aber nicht beschränkt auf Abschreibungen, Reparaturen, Zinsen und Steuern, die sich auf das gemeinsame Eigentum beziehen.',
    '7' => '7. Wie sollte ich meine Immobilieninvestmentgesellschaft strukturieren?',
    '7a' => 'Eine häufig gewählte Art, ein Immobiliengeschäft zu strukturieren, ist die Gründung einer LLC (Gesellschaft mit beschränkter Haftung). Einzelpersonen können sich jedoch auch für eine “S Corp” oder “Sole Proprietorship” entscheiden. LLCs sind in der Immobilieninvestmentbranche am weitesten verbreitet, da es sich um eine separate und eigenständige juristische Einheit handelt. Das bedeutet, dass eine LLC unter ihrem eigenen Namen eine Steueridentifikationsnummer erhält, ein Bankkonto eröffnet und Geschäfte tätigen kann. Der Hauptvorteil einer LLC besteht darin, dass ihre Eigentümer, die sogenannten Mitglieder, eine "beschränkte Haftung" haben, was bedeutet, dass sie in den meisten Fällen nicht persönlich für die Schulden und Verbindlichkeiten der LLC haften.',
    '8' => '8. Wie finde ich Leads für meinen ersten Deal?',
    '8a' => 'In der heutigen Zeit sind Social Media einer der effektivsten und billigsten Wege für neue Investoren, Leads zu finden. Durch die Erstellung von Konten auf allen Websites für soziale Medien können Sie Ihre Marke, Dienstleistungen und einzigartigen Eigenschaften bewerben, die Sie dazu bringen, sich besser als Ihre Mitbewerber zu verkaufen. Content-Marketing ist eine weitere Möglichkeit, sich als Vordenker in der Branche zu etablieren. Das Erstellen von Originalinhalten beweist, dass Sie ein Experte in Ihrer Nische sind und Sie von anderen Investoren trennen. Obwohl Blogging zeitaufwendig sein kann, ist es die Mühe wert, da es freie Leads anziehen kann. Weil es so viele Optionen gibt, wenn es um Immobilien-Marketing-Strategien geht, hängt es letztlich davon ab, wie viel Geld und Zeit Sie ausgeben wollen.In der heutigen Zeit sind Social Media einer der effektivsten und billigsten Wege für neue Investoren, Leads zu finden. Durch die Erstellung von Konten auf allen Websites für soziale Medien können Sie Ihre Marke, Dienstleistungen und einzigartigen Eigenschaften bewerben, die Sie dazu bringen, sich besser als Ihre Mitbewerber zu verkaufen. Content-Marketing ist eine weitere Möglichkeit, sich als Vordenker in der Branche zu etablieren. Das Erstellen von Originalinhalten beweist, dass Sie ein Experte in Ihrer Nische sind und Sie von anderen Investoren trennen. Obwohl Blogging zeitaufwendig sein kann, ist es die Mühe wert, da es freie Leads anziehen kann. Weil es so viele Optionen gibt, wenn es um Immobilien-Marketing-Strategien geht, hängt es letztlich davon ab, wie viel Geld und Zeit Sie ausgeben wollen.',
    '9' => '9. Was muss ich wissenm wenn ich zum ersten mal ein Eigenheim erwerbe?',
    '9a' => 'Sein erstes eigenes Zuhause zu kaufen kann erschreckend und überwältigend sein, aber einmal abgeschlossen, von unschätzbarem Wert. Der erste Schritt für einen neuen Eigenheimkäufer ist es, Ihre Finanzen in Ordnung zu bringen. Es ist wichtig, Ihren Kredit-Score zu überprüfen, um den Gesamtzustand Ihrer Ressourcen zu bestimmen. Der nächste Schritt ist, für einen Kredit vorgenehmigt zu werden. Um dies zu tun, wird Ihr Kreditgeber unter anderem Ihr Verhältnis von Schulden zu Einkommen bewerten, um zu bestimmen, wie viel Sie ausleihen dürfen. Es ist wichtig zu bedenken, dass es einen großen Unterschied zwischen Vorqualifikation und Vorabgenehmigung gibt. Fast jeder wird sich für eine bestimmte Art von Darlehen qualifizieren, aber wenn Sie vorab genehmigt werden, erhalten Sie ein genaueres Bild davon, wie viel Geld Sie erhalten. Der Rest der Schritte wird in unserer Checkliste für den ersten Eigenheimkauf beschrieben.',
    '10' => '10. Wie wähle ich den perfekten Namen für mein Immobiliengeschäft?',
    '10a' => 'Sobald Sie Ihr Geschäft und Ihre Fachrichtung etabliert haben, müssen Sie einen Namen auswählen, der die einzigartigen Merkmale Ihres Unternehmens genau beschreibt. Bevor Sie sich für einen Namen entscheiden, sollten Sie nach anderen Unternehmen suchen, die Sie bewundern. Erfahren Sie, wie und warum sie ihren Geschäftsnamen gewählt haben und sehen Sie, ob Sie von der gewonnenen Inspiration profitieren können. Es ist wichtig, einen Namen zu wählen, den Sie leicht vermarkten können. Etwas, das leicht und clever genug ist, um sich daran zu erinnern, aber nicht so vielseitig, dass die Verbraucher über die Branche verwirrt sind. Seien Sie sicher, dass Sie Ihre Wörter mit Bedacht wählen und sich daran erinnern, dass Ihr Name Ihre Marke wird und für immer bei Ihnen bleibt.',

];