<?php

return [

    'title' => 'Risikooffenlegung',
    'text' => 'Offenlegung von Immobilienrisiken',
    'text2' => 'Diese Website dient der allgemeinen Information. Diese Website soll keine Beratung, Empfehlung zu Buchhaltungs-, Rechts-, Regulierungs-, Steuer- oder Anlagefragen bieten. Keine der auf dieser Website enthaltenen Informationen stellen ein Angebot oder eine Aufforderung zum Kauf oder Verkauf eines Wertpapiers oder Fonds in einer Rechtsordnung dar, in der ein solches Angebot oder eine solche Aufforderung rechtmäßig wäre. Die auf dieser Website genannten Dienstleistungen dürfen nur Personen angeboten und verkauft werden, bei denen die CEE Real Estate Group oder ihre Tochtergesellschaften ordnungsgemäß registriert oder von der Registrierung befreit sind.',
    'text3' => 'Investitionen unterliegen bestimmten Risiken, die mit der Immobilienwirtschaft im Allgemeinen verbunden sind, einschließlich: lokaler, nationaler und internationaler wirtschaftlicher Bedingungen; Angebot und Nachfrage von Immobilien; die finanziellen Bedingungen für Mieter, Käufer und Verkäufer von Immobilien; Änderungen der Zinssätze; Änderungen von Umweltgesetzen oder -vorschriften, Planungsgesetzen und anderen staatlichen Aufgaben sowie fiskal- und geldpolitischen Maßnahmen; Änderungen der Grundsteuersätze; negative Entwicklungen in der Wirtschaft, die Reise- und Einzelhandelsaktivitäten beeinträchtigen; nicht versicherte Schäden; höhere Gewalt, terroristische Ereignisse, unterversicherte oder nicht versicherbare Verluste; und andere Faktoren, die außerhalb der angemessenen Kontrolle des Managers liegen. Wie jüngste Erfahrungen gezeigt haben, unterliegen Immobilienvermögen langfristigen zyklischen Trends, die zu einer erheblichen Volatilität der Werte führen. Aufgrund der Konzentration auf Immobilien und immobilienbezogene Anlagen sind die vorgenannten Risiken den Investitionen überproportional ausgesetzt.',
    'text4' => 'Immobilienanlagen können aufgrund der Konzentration auf eine bestimmte Branche oder einen geografischen Sektor einem höheren Marktrisiko ausgesetzt sein. Immobilienanlagen können Risiken unterliegen, einschließlich, aber nicht beschränkt auf, Wertminderungen von Immobilien, Risiken in Bezug auf allgemeine und wirtschaftliche Bedingungen, Wertänderungen der zugrunde liegenden Immobilien, die Eigentum des Fonds sind, und Ausfälle von Kreditnehmern.',
    'text5' => 'Der Wert der Anlagen und die Erträge daraus können schwanken und Ihre Investition ist nicht garantiert. Die Wertentwicklung in der Vergangenheit ist keine Garantie für zukünftige Ergebnisse. Bitte beachten Sie, dass Investitionen in ausländische Märkte besonderen Währungs-, politischen und wirtschaftlichen Risiken unterliegen. Wechselkurse können dazu führen, dass der Wert der zugrunde liegenden ausländischen Anlagen sinkt oder steigt. Anlagen in Schwellenländern können volatiler sein als andere Märkte und das Risiko für Ihr Kapital ist daher größer. Zudem können die wirtschaftlichen und politischen Situationen volatiler sein als in etablierten Volkswirtschaften, und dies kann sich negativ auf den Wert der getätigten Investitionen auswirken.',

];