<?php

return [

    'title' => 'Terms & Bedingungen',
    'text' => 'Diese Website gehört der CEE Real Estate Group (nachfolgend "uns" oder "wir") und wird von ihr betrieben. Durch den Besuch unserer Website und den Zugang zu den Informationen, Ressourcen, Dienstleistungen, Produkten und Tools, die wir zur Verfügung stellen, erklären Sie sich damit einverstanden, dass Sie die folgenden Bedingungen akzeptieren und einhalten, wie in dieser Richtlinie angegeben (im Folgenden als "Nutzervereinbarung" bezeichnet). Wir behalten uns das Recht vor, diese Nutzungsbedingungen von Zeit zu Zeit ohne Ankündigung zu verändern. Sie erkennen an und stimmen zu, dass es in Ihrer Verantwortung liegt, diese Benutzervereinbarung regelmäßig zu überprüfen, um sich mit Änderungen vertraut zu machen. Ihre fortgesetzte Nutzung dieser Website nach solchen Änderungen gilt als Anerkennung und Zustimmung der geänderten Bedingungen.',
    'text2' => 'Verantwortungsvoller Gebrauch ',
    'text3' => 'Durch den Besuch unserer Website und den Zugang zu den Informationen, Ressourcen, Dienstleistungen, Produkten und Tools, die wir Ihnen direkt oder indirekt zur Verfügung stellen (im Folgenden "Ressourcen" genannt), stimmen Sie zu, diese Ressourcen nur für die von (a) Bedingungen dieser Benutzervereinbarung und (b) geltende Gesetze, Vorschriften und allgemein akzeptierte Online-Praktiken oder Richtlinien. Wobei Sie verstehen, dass: i) jegliche Aktivität, die unsere Ressourcen stört oder beeinträchtigt, einschließlich der Server und / oder Netzwerke, in denen sich unsere Ressourcen befinden oder damit verbunden sind, streng verboten ist. ii) der Versuch, unsere Ressourcen zu kopieren, zu duplizieren, zu reproduzieren, zu verkaufen, zu handeln oder weiterzuverkaufen, strengstens untersagt ist.',
    'text4' => 'Beschränkung der Gewährleistungen',
    'text5' => 'Durch die Nutzung unserer Website verstehen Sie und stimmen zu, dass alle von uns bereitgestellten Ressourcen nur im vorgefundenen Zustand verfügbar sind. Dies bedeutet, dass wir Ihnen gegenüber nicht garantieren, dass:',
    '1' => 'die Verwendung unserer Ressourcen Ihren Bedürfnissen oder Anforderungen entspricht.',
    '2' => 'die Nutzung unserer Ressourcen ununterbrochen, zeitgerecht, sicher oder frei von Fehlern erfolgt.',
    '3' => 'die durch die Verwendung unserer Ressourcen erhaltenen Informationen korrekt oder zuverlässig sein werden, und',
    '4' => 'andere Mängel in der Funktionsweise oder Funktionalität der von uns bereitgestellten Ressourcen repariert werden. Sie verstehen und stimmen außerdem zu, dass:',
    '5' => 'der Inhalt, der durch die Nutzung unserer Ressourcen heruntergeladen oder anderweitig erworben wurde, auf Ihr eigenes Ermessen und auf eigenes Risiko geschieht und Sie allein für Schäden an Ihrem Computer oder anderen Geräten verantwortlich sind, die durch den Download von Daten entstehen könnten.',
    '6' => 'Keine Informationen oder Ratschläge, weder ausdrücklich noch stillschweigend, mündlich oder schriftlich, die Sie von der CEE Real Estate Group oder durch von uns bereitgestellte Ressourcen erhalten, begründen jegliche Gewährleistung, Garantie oder Bedingungen jeglicher Art, mit Ausnahme der hier ausdrücklich genannten Nutzungsbedingungen.',
    'text6' => 'Haftungsbeschränkung',
    'text7' => 'In Verbindung mit der oben beschriebenen Haftungsbeschränkung erklären Sie ausdrücklich, dass jegliche Ansprüche gegen uns auf den Betrag begrenzt sind, den Sie für die Nutzung von Produkten und / oder Dienstleistungen gezahlt haben. Die CEE Real Estate Group haftet nicht für direkte, indirekte, zufällige, Folge- oder exemplarische Verluste oder Schäden, die Ihnen als Folge der Nutzung unserer Ressourcen oder aufgrund von Änderungen, Datenverlust oder -beschädigung oder Stornierung entstehen, Verlust des Zugriffs oder Ausfallzeiten in dem Umfang, in dem die geltenden Haftungsbeschränkungen gelten.',
    'text8' => 'Beendigung der Nutzung',
    'text9' => 'Sie stimmen zu, dass wir nach eigenem Ermessen Ihren Zugriff auf die gesamte oder einen Teil unserer Website und Ressourcen mit oder ohne vorherige Ankündigung und aus irgendeinem Grund sperren oder beenden können, einschließlich, ohne Einschränkung, eines Verstoßes gegen diese Benutzervereinbarung. Jeder Verdacht auf illegale, betrügerische oder missbräuchliche Aktivitäten kann Grund für die Beendigung Ihrer Beziehung sein und kann an die zuständigen Strafverfolgungsbehörden weitergeleitet werden. Bei einer Aussetzung oder Kündigung erlischt Ihr Recht, die von uns bereitgestellten Ressourcen zu nutzen, und wir behalten uns das Recht vor, jegliche Informationen, die Sie bei uns gespeichert haben, einschließlich aller Konto- oder Login-Daten, zu entfernen oder zu löschen.',
    'text10' => 'Geltendes Recht',
    'text11' => 'Diese Website wird von der CEE Real Estate Group kontrolliert. Es ist für die meisten Länder der Welt zugänglich. Mit dem Zugriff auf unsere Website stimmen Sie zu, dass die Regeln und Gesetze unseres Staates, ungeachtet des Kollisionsrechts und des Übereinkommens der Vereinten Nationen über den internationalen Warenkauf, für alle Angelegenheiten im Zusammenhang mit der Nutzung dieser Website und des Kaufs gelten von jeglichen Produkten oder Dienstleistungen durch diese Seite. Darüber hinaus werden alle Maßnahmen zur Durchsetzung dieser Benutzervereinbarung vor den Bundes- oder Landesgerichten erhoben. Sie stimmen hiermit der persönlichen Zuständigkeit dieser Gerichte zu und verzichten auf jegliche Einwände gegen diesen Gerichtsstand oder Zuständigkeiten vor diesen Gerichten. ',
    'text12' => 'Wir haben weder Kontrolle noch Verantwortung für die Inhalte Dritter',
    'text13' => 'Wir können Links zu anderen Websites bereitstellen, die von Dritten unterhalten werden. Links zu Websites Dritter werden nur zu Ihrer Bequemlichkeit und zur Information bereitgestellt. Der Inhalt einer verlinkten Website unterliegt nicht unserer Kontrolle. Daher sind wir nicht für den Inhalt verantwortlich, einschließlich weiterer Links zu einer Website Dritter. Wenn Sie sich dazu entschließen, auf eine dieser Websites zuzugreifen, die mit unserer Website verlinkt sind, tun Sie dies ausschließlich auf eigene Gefahr. Es liegt an Ihnen, Vorkehrungen zu treffen, um sicherzustellen, dass der Drittanbieter, zu dem Sie eine Verbindung herstellen, frei von Computerviren und anderen obstruktiven Elementen ist. Wir behalten uns das Recht vor, einen Link zu einer Website eines Drittanbieters jederzeit zu beenden. Die Tatsache, dass wir einen Link zu einer Website eines Drittanbieters bereitstellen, bedeutet nicht, dass wir diese Website autorisieren oder unterstützen. Es bedeutet auch nicht, dass wir mit Drittanbietern Websites Eigentümer oder Sponsoren verbunden sind. Wenn ein Dritter auf unsere Website verlinkt, ist dies nicht unbedingt ein Hinweis auf eine Bestätigung, Genehmigung, Sponsoring, Mitgliedschaft, ein Gemeinschaftsunternehmen oder Partnerschaft von oder mit uns. In den meisten Fällen sind wir uns nicht bewusst, dass Dritte Links zu unserer Website bereitstellen.',
    'text14' => 'Wir bieten keine Wertpapiere an oder bieten Anlageberatung an',
    'text15' => 'Nichts auf dieser Website stellt eine Anlageberatung dar. Wir stellen Investor-Relations-Material zu Ihrer Bequemlichkeit und Information zur Verfügung. Darüber hinaus stellen das Investor-Relations-Material und die anderen Inhalte auf unserer Website keine Angebote zum Verkauf oder Aufforderung zum Verkauf oder eine Aufforderung zum Kauf eines Wertpapiers dar.',
    'text16' => 'Warenzeichen und Copyright',
    'text17' => 'Bestimmte Namen, Grafiken, Logos, Symbole, Designs, Wörter, Titel oder Sätze auf dieser Website können Handelsnamen oder Marken der CEE Real Estate Group sein. Die Darstellung einer Marke auf dieser Website bedeutet nicht, dass eine Lizenz zur Nutzung der Marke erteilt wurde. Alle Informationen auf dieser Website sind durch die Urheberrechtsgesetze der Vereinigten Staaten und anderer Länder geschützt. Wenn nicht anders angegeben, erlaubt Ihnen die Nutzung dieser Website nicht, Informationen auf den Seiten dieser Website zu kopieren, zu reproduzieren, neu zu verteilen oder in irgendeiner Form neu zu veröffentlichen. Jeder Benutzer, der ohne vorherige schriftliche Genehmigung von Marken, Markenzeichen und / oder Urheberrechte des Bundes oder des Gewohnheitsrechts verletzen oder kopiert, kann gerichtlich verfolgt werden. Die Anzeige von Markenzeichen auf dieser Website ist strafbar und impliziert nicht, dass eine Lizenz jeglicher Art zur Verwendung der Marke gewährt wurde. Alle Informationen auf dieser Website sind durch die Urheberrechtsgesetze der Vereinigten Staaten und anderer Länder geschützt. Wenn nicht anders angegeben, erlaubt Ihnen die Nutzung dieser Website nicht, Informationen auf den Seiten dieser Website zu kopieren, zu reproduzieren, neu zu verteilen oder in irgendeiner Form neu zu veröffentlichen. Jeder Nutzer, der ohne vorherige schriftliche Genehmigung der CEE Real Estate Group Marken erneut überträgt, kopiert oder ändert, kann gegen Marken- und / oder Urheberrechtsgesetze des Bundes oder des Common Law verstoßen und kann gerichtlich verfolgt werden.',
    'text18' => 'Garantie',
    'text19' => 'SOWEIT NICHT ANDERS AUSDRÜCKLICH AUSGESCHLOSSEN WIRD, SCHLIESST CEE Real Estate Group AUSDRÜCKLICH ALLE GEWÄHRLEISTUNGEN UND BEDINGUNGEN IRGENDEINER ART AUS, OB AUSDRÜCKLICH ODER STILLSCHWEIGEND, EINSCHLIESSLICH, ABER NICHT BESCHRÄNKT AUF DIE STILLSCHWEIGENDEN GEWÄHRLEISTUNGEN UND BEDINGUNGEN DER MARKTFÄHIGKEIT, EIGNUNG FÜR EINEN BESTIMMTEN ZWECK UND NICHTVERLETZUNG VON RECHTEN.',
    'text20' => 'Kontakt Informationen',
    'text21' => 'Wenn Sie Fragen oder Anmerkungen zu diesen oben beschriebenen Nutzungsbedingungen haben, können Sie uns über die Kontaktdaten auf unserer Kontaktseite erreichen.'

];